import React, { useState } from 'react';
import { Sparkles, CheckCircle2, ChevronRight, Award, Compass, Lightbulb } from 'lucide-react';
import { useApp } from '../context/AppContext';
import confetti from 'canvas-confetti';

export const RecommendationsPage: React.FC = () => {
  const { recommendations, toggleRecommendation } = useApp();
  
  const [filterCategory, setFilterCategory] = useState('all');
  const [filterDifficulty, setFilterDifficulty] = useState('all');

  // Calculate stats
  const totalPotentialSavings = recommendations.reduce((sum, r) => sum + r.estSavings, 0);
  const totalAppliedSavings = recommendations
    .filter(r => r.applied)
    .reduce((sum, r) => sum + r.estSavings, 0);

  const handleApply = async (id: string, currentlyApplied: boolean) => {
    await toggleRecommendation(id);
    
    // Celebrate if applying it
    if (!currentlyApplied) {
      confetti({
        particleCount: 50,
        angle: 60,
        spread: 55,
        origin: { x: 0 },
        colors: ['#10B981', '#6D28D9']
      });
      confetti({
        particleCount: 50,
        angle: 120,
        spread: 55,
        origin: { x: 1 },
        colors: ['#10B981', '#6D28D9']
      });
    }
  };

  // Filter list
  const filteredRecs = recommendations.filter(rec => {
    const categoryMatch = filterCategory === 'all' || rec.category === filterCategory;
    const difficultyMatch = filterDifficulty === 'all' || rec.difficulty === filterDifficulty;
    return categoryMatch && difficultyMatch;
  });

  return (
    <div className="space-y-6">
      
      {/* Page Header */}
      <div>
        <h2 className="font-display font-bold text-xl md:text-2xl text-white">
          AI Savings Recommendations
        </h2>
        <p className="text-xs text-slate-400">
          Personalized recommendations generated by AI based on your consumption patterns.
        </p>
      </div>

      {/* Top Savings Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        
        {/* Total savings remaining */}
        <div className="glass-panel p-5 rounded-2xl border border-white/10 flex justify-between items-center text-left">
          <div>
            <span className="text-[9px] text-slate-500 font-bold uppercase block">Monthly Potential Savings</span>
            <span className="text-xl font-display font-bold text-white">₹{totalPotentialSavings}</span>
          </div>
          <Lightbulb className="w-8 h-8 text-primary-light opacity-50" />
        </div>

        {/* Total savings applied */}
        <div className="glass-panel p-5 rounded-2xl border border-white/10 flex justify-between items-center text-left">
          <div>
            <span className="text-[9px] text-slate-500 font-bold uppercase block">Savings Applied Already</span>
            <span className="text-xl font-display font-bold text-success">₹{totalAppliedSavings}</span>
          </div>
          <CheckCircle2 className="w-8 h-8 text-success opacity-50" />
        </div>

        {/* Savings Efficiency Score */}
        <div className="glass-panel p-5 rounded-2xl border border-white/10 flex justify-between items-center text-left">
          <div>
            <span className="text-[9px] text-slate-500 font-bold uppercase block">Efficiency Ratio</span>
            <span className="text-xl font-display font-bold text-accent">
              {totalPotentialSavings > 0 ? Math.round((totalAppliedSavings / totalPotentialSavings) * 100) : 100}%
            </span>
          </div>
          <Award className="w-8 h-8 text-accent opacity-50" />
        </div>

      </div>

      {/* Filter Toolbar */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-4 glass-panel rounded-2xl border border-white/5 bg-surface-dark/50">
        
        {/* Categories */}
        <div className="flex items-center gap-2 overflow-x-auto no-scrollbar">
          <span className="text-[10px] text-slate-500 font-bold uppercase whitespace-nowrap">Category:</span>
          {['all', 'electricity', 'water', 'broadband', 'mobile'].map((cat) => (
            <button
              key={cat}
              onClick={() => setFilterCategory(cat)}
              className={`text-[10px] font-bold px-3 py-1.5 rounded-lg border capitalize transition-all ${
                filterCategory === cat
                  ? 'bg-primary border-primary text-white'
                  : 'bg-surface border-white/5 text-slate-400 hover:text-white'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Difficulty */}
        <div className="flex items-center gap-2">
          <span className="text-[10px] text-slate-500 font-bold uppercase">Difficulty:</span>
          {['all', 'Easy', 'Medium', 'Hard'].map((diff) => (
            <button
              key={diff}
              onClick={() => setFilterDifficulty(diff)}
              className={`text-[10px] font-bold px-3 py-1.5 rounded-lg border capitalize transition-all ${
                filterDifficulty === diff
                  ? 'bg-accent border-accent text-white'
                  : 'bg-surface border-white/5 text-slate-400 hover:text-white'
              }`}
            >
              {diff}
            </button>
          ))}
        </div>

      </div>

      {/* Recommendations Cards List */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {filteredRecs.length === 0 ? (
          <div className="col-span-2 glass-panel p-8 rounded-2xl text-center space-y-4 max-w-sm mx-auto">
            <Compass className="w-12 h-12 text-slate-500 mx-auto" />
            <h3 className="text-sm font-semibold text-white">No Savings Found</h3>
            <p className="text-xs text-slate-400">
              Try adjusting your category or difficulty filters.
            </p>
          </div>
        ) : (
          filteredRecs.map((rec) => (
            <div 
              key={rec.id} 
              className={`glass-panel p-5 rounded-2xl border transition-all duration-300 flex flex-col justify-between text-left space-y-4 relative ${
                rec.applied ? 'border-success/30 bg-success/5' : 'border-white/10 hover:border-white/20'
              }`}
            >
              
              <div className="space-y-2.5">
                <div className="flex justify-between items-start">
                  <span className="text-[9px] font-bold bg-white/5 text-slate-400 border border-white/10 px-2 py-0.5 rounded uppercase">
                    {rec.category}
                  </span>
                  
                  <div className="flex gap-1.5">
                    {/* Difficulty Badge */}
                    <span className={`text-[8px] font-bold px-1.5 py-0.2 rounded uppercase ${
                      rec.difficulty === 'Easy' ? 'bg-success/15 text-success' :
                      rec.difficulty === 'Medium' ? 'bg-warning/15 text-warning' : 'bg-danger/15 text-danger'
                    }`}>
                      {rec.difficulty}
                    </span>
                    {/* Impact Badge */}
                    <span className={`text-[8px] font-bold px-1.5 py-0.2 rounded uppercase ${
                      rec.impact === 'High' ? 'bg-primary/20 text-primary-light' : 'bg-slate-800 text-slate-400'
                    }`}>
                      {rec.impact} Impact
                    </span>
                  </div>
                </div>

                <h4 className="text-xs font-semibold text-white flex items-center gap-1.5">
                  {rec.title}
                  {rec.applied && <span className="inline-block w-2 h-2 rounded-full bg-success"></span>}
                </h4>
                
                <p className="text-[10px] text-slate-400 leading-relaxed font-sans">{rec.description}</p>
              </div>

              <div className="pt-3 border-t border-white/5 flex items-center justify-between">
                <div>
                  <span className="text-[9px] text-slate-500 font-semibold block">Estimated Savings</span>
                  <span className="text-xs font-bold text-success">₹{rec.estSavings}/mo</span>
                </div>

                <button
                  onClick={() => handleApply(rec.id, rec.applied)}
                  className={`px-4 py-2 rounded-xl text-[10px] font-bold transition-all ${
                    rec.applied 
                      ? 'bg-success/20 hover:bg-success/30 text-success border border-success/30' 
                      : 'bg-primary hover:bg-primary-light text-white shadow-md shadow-primary/10'
                  }`}
                >
                  {rec.applied ? 'Applied' : 'Apply Action'}
                </button>
              </div>

            </div>
          ))
        )}
      </div>

    </div>
  );
};
